### ISSUE TITLE
ERROR in ./content/closure-polyfill.js Module build failed: Error: Can't find closure dependency bot 

### ISSUE THREAD

**Issue by vmonisha69** [mxmul/closure-loader#48]
I am trying to compile the selenium-ide-3.4.4 source. I have installed all the dependencies using npm install and update. Also ran **peru sync** command. However, on running **npm run build**
i am getting the following error:

ERROR in ./content/closure-polyfill.js
Module build failed: Error: Can't find closure dependency bot
    at replaceRequire (/root/selenium-ide-3.4.4/packages/selenium-ide/node_modules/closure-loader/lib/index.js:39:15)
    at mapBuilder.then.provideMap (/root/selenium-ide-3.4.4/packages/selenium-ide/node_modules/closure-loader/lib/index.js:253:26)
    at tryCatcher (/root/selenium-ide-3.4.4/packages/selenium-ide/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/root/selenium-ide-3.4.4/packages/selenium-ide/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/root/selenium-ide-3.4.4/packages/selenium-ide/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/root/selenium-ide-3.4.4/packages/selenium-ide/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/root/selenium-ide-3.4.4/packages/selenium-ide/node_modules/bluebird/js/release/promise.js:699:18)
    at Promise._fulfill (/root/selenium-ide-3.4.4/packages/selenium-ide/node_modules/bluebird/js/release/promise.js:643:18)
    at Promise._resolveCallback (/root/selenium-ide-3.4.4/packages/selenium-ide/node_modules/bluebird/js/release/promise.js:437:57)
    at Promise._settlePromiseFromHandler (/root/selenium-ide-3.4.4/packages/selenium-ide/node_modules/bluebird/js/release/promise.js:529:17)
    at Promise._settlePromise (/root/selenium-ide-3.4.4/packages/selenium-ide/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/root/selenium-ide-3.4.4/packages/selenium-ide/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/root/selenium-ide-3.4.4/packages/selenium-ide/node_modules/bluebird/js/release/promise.js:699:18)
    at Promise._fulfill (/root/selenium-ide-3.4.4/packages/selenium-ide/node_modules/bluebird/js/release/promise.js:643:18)
    at MappingPromiseArray.PromiseArray._resolve (/root/selenium-ide-3.4.4/packages/selenium-ide/node_modules/bluebird/js/release/promise_array.js:126:19)
    at MappingPromiseArray._promiseFulfilled (/root/selenium-ide-3.4.4/packages/selenium-ide/node_modules/bluebird/js/release/map.js:101:18)
    at Promise._settlePromise (/root/selenium-ide-3.4.4/packages/selenium-ide/node_modules/bluebird/js/release/promise.js:579:26)
    at Promise._settlePromise0 (/root/selenium-ide-3.4.4/packages/selenium-ide/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/root/selenium-ide-3.4.4/packages/selenium-ide/node_modules/bluebird/js/release/promise.js:699:18)
    at Promise._fulfill (/root/selenium-ide-3.4.4/packages/selenium-ide/node_modules/bluebird/js/release/promise.js:643:18)
    at Promise._resolveCallback (/root/selenium-ide-3.4.4/packages/selenium-ide/node_modules/bluebird/js/release/promise.js:437:57)
    at Promise._settlePromiseFromHandler (/root/selenium-ide-3.4.4/packages/selenium-ide/node_modules/bluebird/js/release/promise.js:529:17)
    at Promise._settlePromise (/root/selenium-ide-3.4.4/packages/selenium-ide/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/root/selenium-ide-3.4.4/packages/selenium-ide/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/root/selenium-ide-3.4.4/packages/selenium-ide/node_modules/bluebird/js/release/promise.js:699:18)
    at Promise._fulfill (/root/selenium-ide-3.4.4/packages/selenium-ide/node_modules/bluebird/js/release/promise.js:643:18)
    at MappingPromiseArray.PromiseArray._resolve (/root/selenium-ide-3.4.4/packages/selenium-ide/node_modules/bluebird/js/release/promise_array.js:126:19)
    at MappingPromiseArray._promiseFulfilled (/root/selenium-ide-3.4.4/packages/selenium-ide/node_modules/bluebird/js/release/map.js:101:18)
    at Promise._settlePromise (/root/selenium-ide-3.4.4/packages/selenium-ide/node_modules/bluebird/js/release/promise.js:579:26)
    at Promise._settlePromise0 (/root/selenium-ide-3.4.4/packages/selenium-ide/node_modules/bluebird/js/release/promise.js:619:10)
 @ ./content/commands-api.js 16:135-164
 @ multi ./content/commands-api

Please assist to resolve this issue

Thanks.

**Comment by mxmul** [comment]
This sounds like user error. `Module build failed: Error: Can't find closure dependency bot` means that somewhere in your code, you have `goog.require("bot")`, but there is no corresponding `goog.provide("bot")` in any of the closure module search paths.

Taking a quick look at the selenium-ide repo, it looks like "bot" is a namespace exported by the selenium library itself, and that the `peru sync` is used to clone parts of that library locally before running the webpack build. I'm guessing something in that build process failed for you, and the `selenium-ide/packages/selenium-ide/src/{selenium-,}atoms` directories were not generated.

I'd suggest following the README in selenium-ide, and directing any questions about its build setup to that project's maintainers. FWIW I was able to compile everything properly by following the steps in their README.
